spring:
  application:
    name: race
  datasource:
    url: jdbc:postgresql://localhost:5432/race_db
    username: race
    password: race
  jpa:
    hibernate:
    # 从 validate 改为 update
      ddl-auto: update
    show-sql: true
  web:
    error:
      include-message: always

  flyway:
    enabled: true  # 从 true 改为 false
